services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault-dev
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: test-token
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s